FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# TODO: fix build errors and use this to avoid using dev server in production:
# RUN npm run build
# CMD ["npm", "start"]

CMD ["npm", "run", "dev"]
