services:
  db:
    image: postgres:16
    restart: always
    ports:
    - ${DB_PORT}:5432
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
        - postgres-volume:/var/lib/postgresql/data
        - ./planty/tests/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
volumes:
  postgres-volume:
