import axios from "axios";

// TODO: use autogenerated types from openapi.json
export async function moveTask(taskData: {
  task_id: string;
  section_to_id: string;
  index: number;
}) {
  try {
    const response = await axios.post("/api/task/move", taskData);
    return response.data;
  } catch (error) {
    alert("Error while moving task, check the console for logs");
    console.error("Error while moving task:", error);
    throw error;
  }
}

export async function updateTask(updateTaskData: {
  id: string;
  title?: string;
  description?: string;
  due_to_next?: string;
  due_to_days_period?: number;
}) {
  try {
    const response = await axios.patch("/api/task", updateTaskData);
    return response.data;
  } catch (error) {
    alert("Error while updating task, check the console for logs");
    console.error("Error while updating task:", error);
    throw error;
  }
}
