"""empty message

Revision ID: e99e87b2e1c8
Revises: 
Create Date: 2024-07-13 20:59:16.185222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from planty.infrastructure.utils import GUID

# revision identifiers, used by Alembic.
revision: str = 'e99e87b2e1c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('parent_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('task',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('section_id', GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('due_to_next', sa.Date(), nullable=True),
    sa.Column('due_to_days_period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('user')
    op.drop_table('section')
    # ### end Alembic commands ###
